name: Sequential Deployment with Environments

on:
  push:
    branches:
      - main
    paths:
      - 'security/**'
  workflow_dispatch:

jobs:
  deploy_to_development:
    runs-on: ubuntu-latest
    environment: 
      name: development
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure AWS Credentials for Development
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Adjust as per your AWS region
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0
      - name: Deploy to Development
        run: |
          terraform init
          terraform apply -auto-approve
        working-directory: ./security/environments/development

  deploy_to_production:
    needs: deploy_to_development
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'workflow_dispatch'
    environment: 
      name: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure AWS Credentials for Production
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Adjust as per your AWS region
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0
      - name: Deploy to Production
        run: |
          terraform init
          terraform apply -auto-approve
        working-directory: ./security/environments/production
