name: Deploy Remote State

on:
  workflow_dispatch:
   inputs:
     environment:
       required: true
       description: Select Environment
       type: choice
       options:
       - development
       - production

jobs:
  deploy_remote_state:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure AWS Credentials for Development
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0
      - name: Deploy to Development
        run: |
          terraform init
          terraform apply -auto-approve
        working-directory: ./security/environments/${{ github.event.inputs.environment }}/remote-state
