name: Deploy Security Resources

on:
  push:
    branches:
      - main
    paths:
      - 'security/**'
  workflow_dispatch:
    inputs:
      target_environment:
        description: 'Target environment for manual deployment (e.g., production)'
        required: true
        default: 'production'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event_name == 'push' && 'development' || github.event.inputs.target_environment }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Terraform Init
      run: terraform init
      working-directory: ./security/environments/${{ github.event_name == 'push' && 'development' || 'production' }}

    - name: Terraform Plan
      run: terraform plan
      working-directory: ./security/environments/${{ github.event_name == 'push' && 'development' || 'production' }}

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ./security/environments/${{ github.event_name == 'push' && 'development' || 'production' }}
